//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generoes
    {
        public Generoes()
        {
            this.Excurcaos = new HashSet<Excurcaos>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descrição { get; set; }
    
        public virtual ICollection<Excurcaos> Excurcaos { get; set; }
    }
}
