//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guias
    {
        public Guias()
        {
            this.Excurcaos = new HashSet<Excurcaos>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int Idade { get; set; }
        public string Sexo { get; set; }
        public string Cpf { get; set; }
        public string Rg { get; set; }
    
        public virtual ICollection<Excurcaos> Excurcaos { get; set; }
    }
}
