//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensOrdems
    {
        public int IdOrdemDetalhe { get; set; }
        public int IdOrdem { get; set; }
        public int ExcurcaoId { get; set; }
        public int Quantidade { get; set; }
        public decimal PrecoUnitario { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> Ordem_OrdemId { get; set; }
        public Nullable<int> Ordem_OrdemItem { get; set; }
    
        public virtual Excurcaos Excurcaos { get; set; }
        public virtual Ordems Ordems { get; set; }
    }
}
