//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripSystemEntities : DbContext
    {
        public TripSystemEntities()
            : base("name=TripSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Carrinhoes> Carrinhoes { get; set; }
        public DbSet<Contatoes> Contatoes { get; set; }
        public DbSet<Excurcaos> Excurcaos { get; set; }
        public DbSet<Generoes> Generoes { get; set; }
        public DbSet<Guias> Guias { get; set; }
        public DbSet<ItensOrdems> ItensOrdems { get; set; }
        public DbSet<Ordems> Ordems { get; set; }
        public DbSet<Reservas> Reservas { get; set; }
        public DbSet<Transportadoras> Transportadoras { get; set; }
        public DbSet<Veiculoes> Veiculoes { get; set; }
    }
}
