//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculoes
    {
        public Veiculoes()
        {
            this.Excurcaos = new HashSet<Excurcaos>();
        }
    
        public int VeiculoId { get; set; }
        public int TransportadoraId { get; set; }
        public string MarcaCarro { get; set; }
        public string ModeloCarro { get; set; }
        public int QntAssentos { get; set; }
        public double ValorDiaria { get; set; }
    
        public virtual ICollection<Excurcaos> Excurcaos { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
    }
}
